fundr/fundr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

fundr/main_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
  path('', views.login, name='login'),
  path('home', views.home, name='home'),
  path('explore/', views.explore, name='explore'),
  path('following/', views.following, name='following'),
  path('about/', views.about, name='about'),
  path('contact/', views.contact, name='contact'),
  path('terms/', views.terms, name='terms'),
  path('settings/', login_required(views.SettingsView.as_view()), name='settings'),
  path('fundrs/<int:fundr_id>', views.fundrs_detail, name='detail'),
  path('fundrs/<int:fundr_id>/add_post/', views.add_post, name='add_post'),
  path('accounts/signup/', views.signup, name='signup'),
  path('your_fundrs/', views.your_fundrs, name='your_fundrs'),
  path('your_fundrs/new_fundr', login_required(views.FundrCreate.as_view()), name='new_fundr'),
  path('fundrs/<int:pk>/update', login_required(views.FundrUpdate.as_view()), name='update_fundr'),
  path('fundrs/<int:pk>/delete', login_required(views.FundrDelete.as_view()), name='delete_fundr'),
  path('userlocation/', views.store_user_location, name='store_user_location'),
  path('fundrs/<int:fundr_id>/posts/<int:post_id>', views.delete_post, name='delete_post'),
  path('settings/update/<int:pk>', login_required(views.SettingsUpdate.as_view()), name='update_settings'),
  path('settings/update/<int:user_id>', views.add_avatar, name='add_avatar'),
]

fundr/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _
import datetime

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=200)
    location = models.CharField(max_length=7, default="")
    latitude = models.FloatField(default=0.0, null=True)
    longitude = models.FloatField(default=0.0, null=True)
    catchment = models.FloatField(default=100)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


    

class Fundraiser(models.Model):
    name = models.CharField(max_length = 100)
    bio  = models.CharField(max_length = 280)
    description = models.CharField(max_length = 1000)
    image = models.CharField(max_length=200, default="https://fundr.fly.dev/static/main_app/home_pic.png", null=True, blank=True)
    goal = models.FloatField(
        default=1000.0,
        validators=[
            MaxValueValidator(100000,0),
            MinValueValidator(10.0)
            ]
        )
    current = models.FloatField(
        default=0.0,
        validators=[
            MinValueValidator(0.0)
        ]
        )
    location = models.CharField(max_length=7,)
    lat = models.FloatField(default=0.0)
    long = models.FloatField(default=0.0)
    distance_from_user = models.FloatField(default=0.0)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE) 
    followers = models.ManyToManyField(User)
    # deletes all fundraisers when owners account is deleted // poses some opportunities for would-be scammers -- future implementation should have an archive database that holds details of fundraisers and their owners (beyond scope given timeframe)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
      return reverse('detail', kwargs={'fundr_id': self.id})
    

class Post(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    fundraiser = models.ForeignKey(Fundraiser, on_delete=models.CASCADE)
    image = models.CharField(max_length=200, default="https://fundr.fly.dev/static/main_app/home_pic.png")
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    date_created = models.DateField(_("Date"), default=datetime.date.today)

    def __str__(self):
        return self.content
    
    
    

fundr/main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import User, Profile, Fundraiser, Post

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'location')
    
    
class FundrForm(ModelForm):
    class Meta:
        model = Fundraiser
        fields = ('name', 'bio', 'description', 'goal', 'location', 'image')


class PostForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 35, 'class': 'align-self-start form-label'}))
    image = forms.ImageField(required=False)
    owner = forms.IntegerField(required=True, widget=forms.HiddenInput())
    fundraiser = forms.IntegerField(required=True, widget=forms.HiddenInput())


class SettingsForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['catchment',]


class AvatarForm(forms.Form):
    image = forms.ImageField(required=False)

fundr/main_app/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login as login_process
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django import forms
from django.core.files.uploadedfile import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import *
from .models import Fundraiser, Post, Profile
from .helper import *
from PIL import *

import json
import pgeocode
import numpy as np
import datetime
import uuid
import boto3
import os
import datetime
from ukpostcodeutils import validation

# Create your views here.
def home(request): 
  if (request.user.is_authenticated != True): return redirect('/accounts/login/')
  template = is_mobile(request)

  user = request.user
  
  posts = []
  fundrs = User.objects.get(id=request.user.id).fundraiser_set.all()

  for fundr in fundrs:
    post_list = list(Post.objects.filter(fundraiser=fundr.id))
    posts.extend(post_list)

  sorted_list = list(reversed(sorted(posts, key=lambda x: x.date_created)))
  page = request.GET.get('page', 1)
  paginator = Paginator(sorted_list, 3)

  try:
      posts = paginator.page(page)
  except PageNotAnInteger:
      posts  = paginator.page(1)
  except EmptyPage:
      posts = paginator.page(paginator.num_pages)

  return render(request, 'home.html', { 'template' : template, 'posts': posts, 'title': 'Home', 'user': user })


def signup(request):
  error_message = ''

  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)

    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login_process(request, user)
      return redirect('home')
    
    else:
      error_message = 'Invalid sign up - try again'

  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  
  context = {'form': form, 'error_message': error_message, 'title': 'Sign-up'}

  return render(request, 'registration/signup.html', context)


def explore(request):
  if (request.user.is_authenticated != True): return redirect('/accounts/login/')
  template = is_mobile(request)

  if request.method == 'POST':
    fundr_id = request.POST.get("fundr_id")
    current_index = int(request.POST.get("current_index"))
    Fundraiser.objects.get(id=fundr_id).followers.add(request.user)

  else: 
    current_index = 0

  user = Profile.objects.get(user_id=request.user.id)
  user_location = np.array([[user.latitude, user.longitude]])
  fundrs = Fundraiser.objects.all()
  
  for fundr in fundrs:
    fundr_location = np.array([[fundr.lat, fundr.long]])
    distance = np.round(pgeocode.haversine_distance(fundr_location, user_location),1)
    floats = [float(np_float) for np_float in distance]
    fundr.distance_from_user = floats[0]
    fundr.save()
  
  fundrs = Fundraiser.objects.filter(distance_from_user__lte=user.catchment)
  fundrs = fundrs.order_by('distance_from_user','id')
  fundrs = fundrs[current_index:]

  serialized_fundrs = serializers.serialize('json', fundrs)
  return render(request, 'explore.html', { 'template' : template, 'fundrs': json.dumps(serialized_fundrs), "current_index": current_index, 'title': 'Explore', 'fundr_list': fundrs })


def following(request):
  if (request.user.is_authenticated != True): return redirect('/accounts/login/')
  template = is_mobile(request)

  fundrs = User.objects.get(id=request.user.id).fundraiser_set.all()
  
  return render(request, 'following/index.html', { 'template' : template, 'fundrs': fundrs, 'title': 'Following' })


def your_fundrs(request):
  if (request.user.is_authenticated != True): return redirect('/accounts/login/')
  
  template = is_mobile(request)

  fundrs = Fundraiser.objects.filter(owner_id=request.user.id)
  return render(request, 'fundrs/your_fundrs.html', { 'template' : template, 'fundrs': fundrs, 'title': 'Your Fundrs' })


def store_user_location(request):
  if request.method == 'POST':

    if request.user.is_authenticated:
      #Convert the raw HttpRequest body bytestring into a python dict:
      req_params = json.loads(request.body.decode('utf-8'))
      #Store the user idea of the authenticated user:
      req_user_id = request.user.id
      #Store the lat and lon variables:
      latitude = req_params["userlat"]
      longitude = req_params["userlon"]
      #Get the correct profile object:
      profile_to_update = Profile.objects.get(user_id=req_user_id)
      #Update the profile object:
      profile_to_update.latitude = latitude
      profile_to_update.longitude = longitude
      profile_to_update.save()
      return JsonResponse({'message': 'Location stored successfully'})
    
    else:
        return JsonResponse({'error': 'User not authenticated'}, status=401)
    
  else:
    return JsonResponse({'error': 'Invalid request method'})


class FundrCreate(CreateView):
  model = Fundraiser
  form_class= FundrForm
  # success_url = '/your_fundrs'
  template_name = 'fundrs/new_fundr.html'

  def get(self, request, *args, **kwargs):
    # Access the request object here
    # You can perform any necessary operations with the request
    self.request = request
    if (request.user.is_authenticated != True):
      return redirect('/accounts/login/')
    # Call the parent class's get() method to handle form-related logic
    return super().get(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    template = is_mobile(self.request)
    context['template'] = template
    # Access the request object through self.request here
    # You can add additional context variables based on the request

    return context
  
  def form_valid(self, form):
    nomi = pgeocode.Nominatim('gb')
    post_code = formatPostcode(form.instance.location).upper()
    form.instance.lat = nomi.query_postal_code(post_code).latitude
    form.instance.long = nomi.query_postal_code(post_code).longitude
    form.instance.owner = self.request.user.profile
    fundr_photo_file = self.request.FILES.get('image')

    if not validation.is_valid_postcode(post_code.replace(' ', '')):
      messages.error(self.request, 'Not a valid postcode')
      return redirect('/your_fundrs/new_fundr')
    
    if form.instance.goal < 100 or form.instance.goal > 100000:
      messages.error(self.request, 'Goals can be between £100 and £100,000')
      return redirect('/your_fundrs/new_fundr')

    if fundr_photo_file:
        # Upload the image to S3
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + fundr_photo_file.name[fundr_photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(fundr_photo_file, bucket, key)
            image_url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            form.instance.image = image_url
        except Exception as e:
            print('An error occurred uploading file to S3:', str(e))

    return super().form_valid(form)
  

class FundrUpdate(UpdateView):
  model = Fundraiser
  form_class = FundrForm
  template_name = 'fundrs/new_fundr.html'

  def get(self, request, *args, **kwargs):
    # Access the request object here
    # You can perform any necessary operations with the request
    self.request = request

    if (request.user.is_authenticated != True):
      return redirect('/accounts/login/')
    
    f = Fundraiser.objects.get(id=kwargs.get('pk'))
    if (self.request.user.profile != f.owner):
      return redirect('/home')
    
    # Call the parent class's get() method to handle form-related logic
    return super().get(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    
    template = is_mobile(self.request)
    context['template'] = template
    # Access the request object through self.request here
    # You can add additional context variables based on the request
    return context

  def form_valid(self, form):
    post_code = form.instance.location.strip(' ')
    id = self.kwargs.get('pk')

    if not validation.is_valid_postcode(post_code):
      messages.error(self.request, 'Not a valid postcode')
      return redirect('/fundrs/{}/update'.format(id))
    
    if form.instance.goal < 100 or form.instance.goal > 100000:
      messages.error(self.request, 'Goals can be between £100 and £100,000')
      return redirect('/fundrs/{}/update'.format(id))
    
    return super().form_valid(form)
  

class FundrDelete(DeleteView):
  model = Fundraiser
  success_url = '/your_fundrs/'


def fundrs_detail(request, fundr_id):
  template = is_mobile(request)
  following = False
  fundr = Fundraiser.objects.get(id=fundr_id)

  if (fundr.followers.filter(id=request.user.id).exists()):
    following = True

  if request.method == 'POST':
    fundr_id = request.POST.get('fundr_id')

    if following == True:
      Fundraiser.objects.get(id=fundr_id).followers.remove(request.user)
      following = False

    else:
      Fundraiser.objects.get(id=fundr_id).followers.add(request.user)
      following = True

  nomi = pgeocode.Nominatim('gb')
  post_code = formatPostcode(fundr.location).upper()
  placename = nomi.query_postal_code(post_code).place_name
  post_form = PostForm()
  user = request.user
  fundr_posts = Post.objects.filter(fundraiser_id=fundr_id)

  return render(request, 'fundrs/detail.html', {
    'fundr': fundr,
    'template' : template,
    'placename': placename,
    'post_form': post_form,
    'user': user,

fundr/main_app/templates/fundrs/detail.html
{% extends template %}
{% load static %}
{% block content %}

<!-- <div class="container child-scroll"> -->
  
  <div class="card ms-3 mb-5" style="width: 95%;">
    <img src="{{ fundr.image }}" class="card-img-top">
    <div class="card-body">
      <h5 class="card-title py-2">{{ fundr.name }}</h5>
      <div class="d-flex py-2">
        <p class="flex-grow-1 text-start fw-semibold">Goal:</p>
        <p>£{{ fundr.current }} of</p>
        <p class="ps-2">£{{ fundr.goal }}</p>
      </div>
      <div class="d-flex py-2">
        <p class="flex-grow-1 text-start fw-semibold">Near to:</p>
        <p>{{ placename }}</p>
      </div>
      <div class="d-flex py-2">
        <p class="flex-grow-1 text-start fw-semibold">Owner</p>
        <p>{{ fundr.owner }}</p>
      </div>
      <p class="card-text text-start">{{ fundr.bio }}</p>
      <p class="card-text fs-6 text-start fw-semibold">Full description:</p>
      <p class="card-text text-start">{{ fundr.description }}</p>
      <form action="" method="POST">
        {% csrf_token %}
        <button type="submit" style="float:right" class="btn accent-clr" id="save-button" name="fundr_id"
          value="{{ fundr.id }}">
          {% if following %}
          UNSAVE
          {% else %}
          SAVE
          {% endif %}
        </button>
      </form>

      {% if user.id == fundr.owner_id %}
      
       
      
      
      <button type="button" style='float: left;' class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
        DELETE
      </button>
       <a href="{% url 'update_fundr' fundr.id%}"  style='float: center;' class="btn btn-warning" >
        UPDATE</a>
      
      


      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are your sure you want to DELETE {{fundr.name}}</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

              <form action="{% url 'delete_fundr' fundr.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" style='float: left;' class="btn btn-danger " value="Delete Fundr">Confirm
                  DELETE</button>


              </form>

            </div>
          </div>
        </div>
      </div>


      {% endif %}

    </div>
  </div>

  {% if user.id == fundr.owner_id %}

  <div class="card ms-3 mb-5" style="width: 95%;">
    <h5 class="card-title py-4">Add a post to this Fundr</h5>
    <form class="d-flex flex-column align-items-center ms-3" style="width: 90%" enctype="multipart/form-data"
      action="{% url 'add_post' fundr.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="owner" id="id_owner" value="{{ fundr.owner_id }}">
      <input type="hidden" name="fundraiser" id="id_fundraiser" value="{{ fundr.id }}">
      {% for field in post_form.visible_fields %}
      <div class="mb-3 d-flex flex-column" style="width: 95%">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}" class="align-self-start form-label">{{ field.label }}</label>
        {{ field }}
      </div>
      {% endfor %}
      <input type="submit" value="Submit" class="btn btn-primary">
      <br>
    </form>
  </div>

  {% endif %}

  {% if posts.count %}
<div class="mb-5"  style="border-bottom: 1px solid grey" ></div>
  {% for post in posts.all %}
  <div class="card ms-3 mb-5" style="width: 95%;">
    <img src="{{ post.image }}" class="card-img-top">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h4 class="card-title py-4">{{ post.title }}</h4>
        <p class="card-title py-4">{{ fundr.owner }}</p>
      </div>
      <div class="d-flex py-2">
        <p class="flex-grow-1 text-start fw-semibold">Posted:</p>
        <p>{{ post.date_created }}</p>
      </div>
      <p class="card-text text-start">{{ post.content }}</p>
    </div>
    {% if user.id == fundr.owner_id %}
    <div class="p-4">
      <a href="{% url 'delete_post' post_id=post.id fundr_id=fundr.id %}"
        class="btn btn-danger px-4 float-end mt-4">Delete</a>
    </div>
    {% endif %}
  </div>
  {% endfor %}
  {% endif %}

<!-- </div> -->

{% endblock %}

fundr/main_app/templates/fundrs/new_fundr.html
{% extends template %}
{% block content %}
{% if object %}
<h1></h1>
{% endif %}
<h2>Start a new Fundr</h2>
<div class="mt-3 d-flex flex-column justify-content-start text-start">
  <form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">Name of Fundr</label>
      <input value="{% if object %}{{ object.name }}{% endif %}" type="text" name="name" maxlength="100" required
        class="form-control" id="id_name" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="id_bio" class="form-label">Bio</label>
      <input value="{% if object %}{{ object.bio }}{% endif %}" type="text" maxlength="280" name="bio" required
        class="form-control" id="id_bio">
      <div id="emailHelp" class="form-text">Short bio to show on your explore card (max. 280ch)</div>
    </div>
    <div class="mb-3">
      <label for="id_description" class="form-label">Description</label>
      <textarea type="text" maxlength="1000" name="description" required class="form-control description"
        id="id_description">{% if object %}{{ object.description }}{% endif %}</textarea>
      <div id="emailHelp" class="form-text">Long description to be displayed on your Fundr page</div>
    </div>
    <div class="mb-3">
      <label for="id_goal" class="form-label">Goal</label>
      <input value="{% if object %}{{ object.goal }}{% endif %}" type="number" name="goal" value="1000.0" max="100000.0"
        required class="form-control" id="id_goal">
    </div>
    <div class="mb-3">
      <label for="id_location" class="form-label">Postcode</label>
      <input value="{% if object %}{{ object.location }}{% endif %}" type="text" maxlength="7" name="location"
        class="form-control" required id="id_location">
    </div>

    <div class="mb-3">
      <label for="id_image" class="form-label">Image</label>
      <input value="{% if object %}{{ object.image }}{% endif %}" type="file" name="image" accept="image/*" id="id_image">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }} error-msg" {% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock %}

fundr/main_app/templates/fundrs/your_fundrs.html
{% extends template %}
{% block content %}

<h2>Your Fundrs</h2>
<p class="lead">Check the progress of your Fundrs here, or create a new one.</p>
<a href="{% url 'new_fundr' %}"><button class="btn btn-primary z-2 my-5">New Fundr</button></a> 



{% for fundr in fundrs %}
  <div class="card ms-2 my-3 " style="width: 95%;">
    <img src="{{ fundr.image }}" class="card-img-top">
    <div class="card-body">
      <a href="{% url 'detail' fundr.id %}" class="text-decoration-none">
        <h3>{{ fundr.name }}</h3>
      </a>
      <p class="card-text text-start">£{{ fundr.current }}/£{{ fundr.goal }}</p>
    </div>
    </div>

{% endfor %}


{% endblock %}